stages:
  - build
  - test
  - lint
  - deploy
  - notify

build:
  stage: build
  tags:
    - devops-test
  script:
    - echo "Сборка приложения..."

test:
  stage: test
  tags:
    - devops-test
  script:
    - echo "Запуск тестов..."
    - python -m unittest discover app/tests

lint:
  stage: lint
  tags:
    - devops-test
  image: python:3.9
  script:
    - pip install flake8
    - flake8 app/

deploy_staging:
  stage: deploy
  tags:
    - devops-test
  image: python:3.9
  script:
    - apt-get update && apt-get install -y docker-compose
    - echo "Остановка предыдущих контейнеров (если есть)..."
    - docker rm -f app-staging || true
    - echo "Деплой приложения на staging через Docker (через docker.sock)..."
    - docker-compose up -d
  only:
    - main

notify:
  stage: notify
  tags:
    - devops-test
  script:
    - echo "Отправка уведомления в Telegram..."
    - >
      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
      -d "chat_id=${TELEGRAM_CHAT_ID}&text=Пайплайн %24CI_PIPELINE_ID завершился со статусом: %24CI_JOB_STATUS"
  when: always
